[package]
name = "dmate-desktop"
version = "1.0.0"
description = "DMate - 离散数学智能辅学系统"
authors = ["DMate"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
